version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gym-plan-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=gym-plan

volumes:
  mongodb_data: